// Code generated by entc, DO NOT EDIT.

package user

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"

	// EdgeHistorytaking holds the string denoting the historytaking edge name in mutations.
	EdgeHistorytaking = "historytaking"

	// Table holds the table name of the user in the database.
	Table = "users"
	// HistorytakingTable is the table the holds the historytaking relation/edge.
	HistorytakingTable = "nurses"
	// HistorytakingInverseTable is the table name for the Nurse entity.
	// It exists in this package in order to avoid circular dependency with the "nurse" package.
	HistorytakingInverseTable = "nurses"
	// HistorytakingColumn is the table column denoting the historytaking relation/edge.
	HistorytakingColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldEmail,
	FieldPassword,
}

var (
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
)
