// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Historytaking is the predicate function for historytaking builders.
type Historytaking func(*sql.Selector)

// Nurse is the predicate function for nurse builders.
type Nurse func(*sql.Selector)

// Patientrecord is the predicate function for patientrecord builders.
type Patientrecord func(*sql.Selector)

// Symptomseverity is the predicate function for symptomseverity builders.
type Symptomseverity func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
