// Code generated by entc, DO NOT EDIT.

package patientrecord

const (
	// Label holds the string label denoting the patientrecord type in the database.
	Label = "patientrecord"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"

	// EdgeHistorytaking holds the string denoting the historytaking edge name in mutations.
	EdgeHistorytaking = "historytaking"

	// Table holds the table name of the patientrecord in the database.
	Table = "patientrecords"
	// HistorytakingTable is the table the holds the historytaking relation/edge.
	HistorytakingTable = "historytakings"
	// HistorytakingInverseTable is the table name for the Historytaking entity.
	// It exists in this package in order to avoid circular dependency with the "historytaking" package.
	HistorytakingInverseTable = "historytakings"
	// HistorytakingColumn is the table column denoting the historytaking relation/edge.
	HistorytakingColumn = "patientrecord_id"
)

// Columns holds all SQL columns for patientrecord fields.
var Columns = []string{
	FieldID,
	FieldName,
}
